name: lcmtv_app
description: "LCMTV Video Streaming App - A YouTube-like video streaming application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # HTTP & API
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  
  # Video Player
  youtube_player_flutter: ^9.0.0
  
  # UI & Navigation
  go_router: ^14.6.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
  # Local Storage
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication & Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  google_sign_in: ^6.2.1
  
  # Security
  crypto: ^3.0.3
  encrypt: ^5.0.1
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.13
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  
  # Testing
  bloc_test: ^9.1.7
  mockito: ^5.4.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  # Fonts (to be added later)
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700
